@echo off

echo stopping target container if running...
call docker stop scala-spark-container
echo removing target container...
call docker rm scala-spark-container
echo removing target image...
call docker image rm scala-spark-image
echo building image...
call docker build -t scala-spark-image .
echo running image with assigned name...
call docker run -dt -p 7070:7070 --name scala-spark-container scala-spark-image